apiVersion: v1
kind: Service
metadata:
  name: birthday-tracker-service
spec:
  selector:
    app: birthday-tracker
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthday-tracker
spec:
  selector:
    matchLabels:
      app: birthday-tracker
  replicas: 5
  template:
    metadata:
      labels:
        app: birthday-tracker
    spec:
      containers:
      - name: birthday-tracker
        image: "ghcr.io/cartosat/vsw-birthday-tracker:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
