version: "1"

services:
  birthday-tracker:
    image: "ghcr.io/cartosat/vsw-birthday-tracker:latest"
    volumes:
      - static:/workspace/assets
      - media:/workspace/media
    networks:
      - dsnl

  nginx-proxy-server:
    build:
      context: proxy-server-nginx
      dockerfile: Dockerfile
    image: "ghcr.io/cartosat/nginx-proxy-server:latest"
    volumes:
      - static:/static
      - media:/media
    ports:
      - "80:80"
    depends_on:
      - birthday-tracker
    networks:
      - dsnl

networks:
  dsnl:
    name: "dsnl"

volumes:
  static:
  media:
