apiVersion: v1
kind: Service
metadata:
  name: birthday-tracker
spec:
  selector:
    app: birthday-tracker
  ports:
  - protocol: TCP
    port: 8000  # Adjust as per your Django app configuration
    targetPort: 8000  # Adjust as per your Django app configuration
